name: Publish Node.js Package

on:
    release:
        types: [created]

permissions:
    contents: read
    packages: write
    id-token: write

jobs:
    publish-npm-package:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "24"
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: npm ci

            - name: Run package validation
              run: npm pkg fix --dry-run

            - name: Publish to npm
              run: npm publish --provenance --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM_TOKEN }}
